### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by Andy1996247** [AvsThiago/DeepBee-source#15]
On the Deepbee website I can't download the GPU version just the cpu.

**Comment by avsthiago** [comment]
Hi @Andy1996247. The GPU version is missing on the website, indeed. I'll upload it to my drive this week and update the website. Thanks for letting me know.

**Comment by Andy1996247** [comment]
Your so welcome! Thankyou for your wonderful work!

**Comment by avsthiago** [comment]
Hi Andy, sorry for the delay. I just changed the download link in the website. Could you try that out?

https://avsthiago.github.io/DeepBee/downloads/deepbee

**Comment by Andy1996247** [comment]
Hi there. It works thankyou very much
