### ISSUE TITLE
Initial Model creation code

### ISSUE THREAD

**Issue by GeorgeGkinis** [avsthiago/deepbee-source#4]
I looked through your code. 

Impressive!

What I could not find are the methods to create the initial model. It is being loaded by both **train.py** and **detection_and_classification.py**.

I am new to machine learning and would like to see how the model is being implemented.
Is it closed-source?

Maybe i'm missing something...

**Comment by AvsThiago** [comment]
Hi @GeorgeGkinis, it is not closed source. I will add it next week. :)

**Comment by GeorgeGkinis** [comment]
> Hi @GeorgeGkinis, it is not closed source. I will add it next week. :)

Thanks!

**Comment by AvsThiago** [comment]
I found the script I used for the first training, it is [here](https://gist.github.com/AvsThiago/3d7e0ff9f4a7ba0ce37b3a28e9ff9cd9). Once I have more time I will improve this code and include it on the main repository.

**Comment by GeorgeGkinis** [comment]
Thank you mate! 
Gonna check on it!
